---
- hosts: edge
  tasks:
    - name: Installer le package mapr-cldb
      ansible.builtin.yum:
        name: mapr-cldb
        state: present
        update_cache: yes
      become: yes
      tags:
        - installer cldb
