---
- hosts: edge
  tasks:
    - name: Installer le package mapr-mfs
      ansible.builtin.yum:
        name: mapr-mfs
        state: present
        update_cache: yes
      become: yes
      tags:
        - install mfs